id: A0828AA2F
title: A Sādhana of Kurukullā
type: translation
pechas:
- I5DD8B11A
- I7A4E322A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:28.855112
  last_modified_at: 2023-01-04 13:11:28.855118
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I5DD8B11A/0AFE: 888E
  I7A4E322A/19BB: 888E
